name: flutter_baijiayun
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.2.17'

dependencies:
  flutter:
    sdk: flutter
  flutter_baijiayun_platform_interface:
    # path: ../flutter_baijiayun_platform_interface
    git:
      url: "https://github.com/HaijunWei/flutter_baijiayun.git"
      path: "flutter_baijiayun_platform_interface"
  flutter_baijiayun_ios:
    # path: ../flutter_baijiayun_ios
    git:
      url: "https://github.com/HaijunWei/flutter_baijiayun.git"
      path: "flutter_baijiayun_ios"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        default_package: flutter_baijiayun_ios