name: flutter_baijiayun_android
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.2.17'

dependencies:
  flutter:
    sdk: flutter
  flutter_baijiayun_platform_interface:
    # path: ../flutter_baijiayun_platform_interface
    git:
      url: "https://github.com/HaijunWei/flutter_baijiayun.git"
      path: "flutter_baijiayun_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: 

flutter:
  plugin:
    platforms:
      android:
        package: com.haijunwei.flutter_baijiayun_android
        pluginClass: FlutterBaijiayunPlugin
        dartPluginClass: VideoPlayerAndroidPlatform